 version: '2.5'
 services:
   backend:
     restart: always
     build:
       context: ./zvuvon-backend/
       dockerfile: Dockerfile
     command: python3 manage.py runserver 0.0.0.0:8000
     volumes:
       - .:/Zvuvon
     ports:
       - "8000:8000"
     networks:
       - net

  frontend:
    restart: always
    command : yarn start
    build:
      context: ./zvuvon-app/
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - net

networks:
  net:
    driver: bridge