version: "2.5"
services:
  frontend:
    restart: always
    command: yarn start
    build:
      context: ./zvuvon-app/
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend
  backend:
    restart: always
    build:
      context: ./zvuvon-backend/
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
